### PR TITLE
[Feature-fix] [3324] Fix sort on file-view tree

### LINKED ISSUE #3324: [Production] Files View Page file tree not sorting
# Steps 
1. Go to staging.osf.io and log in.
2. Create a new project.
3. Upload files in this specific order: x.txt, y.txt and z.txt
4. Upload files in this specific order: c.txt, b.txt and a.txt
5. Click on b.txt to navigate to the file view page
6. The left file view tree does not properly sort the files by name.

# Expected
File names would show up in alphabetical order, e.g. a.txt, b.txt, c.txt, x.txt, y.txt, z.txt

# Actual
Files show up in the order they were uploaded.

image

### PR DESCRIPTION
**Pull request by hmoco**
## Purpose
Fixes #3324, which was the problem that in file-view, the file tree was not sorted. As suggested by @lyndsysimon, this now also renames the methods being exported by Utils, removing underscores to maintain consistency in naming conventions.

## Changes
This makes it so that if there are no Column titles, the file tree is sorted in 'asc' mode. 
screen shot 2015-06-25 at 3 59 35 pm

## Side Effects
Files will always be sorted in ascending fashion if there is no column titles for all fangorn derived file trees (if and only if the method Fangorn.Utils.orderFiles is called when there are no titles).

### CODE REVIEW

File: website/static/js/fangorn.js [hunk 1]
```diff
@@ -2197,7 +2200,8 @@ Fangorn.Utils = {
     openParentFolders : _openParentFolders,
     dismissToolbar : _dismissToolbar,
     uploadRowTemplate : uploadRowTemplate,
-    resolveIconView: resolveIconView
+    resolveIconView: resolveIconView,
+    orderFolder: _fangornOrderFolder
```
Comment (lyndsysimon) [inline website/static/js/fangorn.js]: `_fangornOrderFolder` begins with an underscore, presumably because it wasn't originally intended to be exported outside the scope of `fangorn.js`. Now that it is being exported (and as `orderFolder`), is there any reason not to rename it `orderFolder`?

My rationale for this is that it would make it more clear that those functions defined with an underscore elsewhere are private members of the module, and make it so a text search for the string `"orderFolder"` would return the definition of the function, instead of just its export.

I don't feel that this is a *necessary* change, but if you disagree I'd like to hear your perspective. Steve, if you read this, don't hold up merging this PR on account of this :)

Also, if you do rename it, consider renaming `_openParentFolders` and `_dismissToolbar` as well, for the same reasons. It's not code that's part of this PR, but it would be easy enough to do them all three at once, and I believe would help make this module a bit more consistent.

**Comment by lyndsysimon** [comment]
First pass complete - no changes necessary. All yours, @sloria.

File: website/static/js/fangorn.js (hunk 1 above)
Comment (hmoco) [inline website/static/js/fangorn.js]: No, that makes sense. Will rename them.

File: website/static/js/fangorn.js [hunk 2]
```diff
@@ -1082,13 +1082,16 @@ function _fangornLazyLoadOnLoad (tree, event) {
  * @this Treebeard.controller
  * @private
  */
-function _fangornOrderFolder(tree) {
+function orderFolder(tree) {
```
Comment (lyndsysimon) [inline website/static/js/fangorn.js]: :heart:
