### PR TITLE
[Feature Fix] Fix table out of screen

### LINKED ISSUE #3152: [Production][Staging]File Revision Table gets cutoff when resizing
## Steps
1. Open a file page where you can see the revisions table
2. Resize to a smaller screen

## Expected
The revisions table would resize appropriately.

## Actual
screen shot 2015-06-11 at 11 19 42 am
The table resizes for most wider widths, at 1100 or smaller the table starts going off the edge of the page while the revisions table header does not.

## Suggestions
Since I have been working in this area recently (osf.io/website/static/js/filepage/revisions.js) I have noticed that it uses an actual table instance that may not be as robust as treebeard or some other method. Switching up the way this table is built may fix this issue.

### PR DESCRIPTION
**Pull request by haoyuchen1992**
### Purpose
Resolved [Trell bug](https://trello.com/c/qO0qasX9/177-file-detail-page-revisions-table-extends-past-border)

Resolved #3152 

### Change
1) Delete margin of panel body
2) Add fixed layout for table

### CODE REVIEW

File: website/static/js/filepage/revisions.js [hunk 1]
```diff
@@ -132,7 +132,7 @@ var FileRevisionsTable = {
     view: function(ctrl) {
         return m('#revisionsPanel.panel.panel-default', [
                 m('.panel-heading.clearfix', m('h3.panel-title', 'Revisions')),
-                m('.panel-body', (function() {
+                m('.panel-body', {style:{'padding-right': '0px','pading-left':'0px'}}, (function() {
```
Comment (sloria) [inline website/static/js/filepage/revisions.js]: Typo here: `padding-left`.

**Comment by sloria** [comment]
Fixed typo during merge :octopus:
