### PR TITLE
Fix Format and Dragging

### LINKED ISSUE #390: [contributors] Interaction between clicking and dragging
Dragging the contributors to change order does not have a space buffer. This means that, if someone clicks the remove button while the mouse is moving just a bit, it will appears as if the button kind of clicked but didn't really. It took a while to nail down what was happening, as I thought maybe it was some kind of issue with the button itself.

Ultimately it rarely comes up, and you tend to re-click without thinking about it. I think, when we want to seriously polish it, the drag action should not overtake the click action unless the drag happens by a certain number of pixels before the mouse release.

### PR DESCRIPTION
**Pull request by Ghalko**
## Proposal
Format fix to stop dragging issues, #390, and remove at least one click.

Previously #2196
Close #390

### CODE REVIEW

File: website/static/js/contribManager.js [hunk 1]
```diff
@@ -59,15 +42,32 @@ var ContributorModel = function(contributor, currentUserCanEdit, pageOwner, isRe
     var self = this;
     $.extend(self, contributor);
 
+    self.permissionList = [
+        {value: 'read', text: 'Read'},
+        {value: 'write', text: 'Read + Write'},
+        {value: 'admin', text: 'Administrator'}
+    ];
+    self.getPermission = function(permission) {
```
Comment (sloria) [inline website/static/js/contribManager.js]: This function is brittle (it would break if the order of `permissionList` changed). Better to search through the Array for where `permission` equals the value of `value`.

File: tests/test_views.py [hunk 2]
```diff
@@ -287,6 +287,40 @@ def test_manage_permissions(self):
         assert_equal(self.project.get_permissions(self.user1), ['read'])
         assert_equal(self.project.get_permissions(self.user2), ['read', 'write', 'admin'])
 
+    def test_manage_permissions_again(self):
```
Comment (sloria) [inline tests/test_views.py]: Thanks

**Comment by sloria** [comment]
Looks good. :+1: Just a minor change and this is good to merge.

**Comment by Ghalko** [comment]
@sloria This goes with the other permissions change that was merged recently.

File: website/static/js/contribManager.js [hunk 3]
```diff
@@ -91,22 +89,19 @@ var ContributorModel = function(contributor, currentUserCanEdit, pageOwner, isRe
...
+        return self.getPermission(permission).text;
     });
 
     self.canRemove = ko.computed(function(){
         return (self.id === pageOwner.id) && !isRegistration;
     });
 
+    self.change = ko.computed(function() {
+        self.permission(self.curPermission().value);
+        var current_val = self.curPermission().value;
```
Comment (sloria) [inline website/static/js/contribManager.js]: > Use lowerCamelCase for variables, properties and function names

Will make this change when I merge.

File: website/static/js/contribManager.js [hunk 4]
```diff
@@ -91,22 +89,19 @@ var ContributorModel = function(contributor, currentUserCanEdit, pageOwner, isRe
...
-                return permission.charAt(0).toUpperCase() + permission.slice(1);
-         }
+        return self.getPermission(permission).text;
     });
 
     self.canRemove = ko.computed(function(){
         return (self.id === pageOwner.id) && !isRegistration;
     });
 
+    self.change = ko.computed(function() {
```
Comment (sloria) [inline website/static/js/contribManager.js]: This can be a `pureComputed`. Will make this change when I merge.

File: website/static/js/contribManager.js [hunk 5]
```diff
@@ -333,7 +324,9 @@ var ContributorsViewModel = function(contributors, adminContributors, user, isRe
                 return !contributor.deleteStaged();
             }),
             function(contributor) {
-                return contributor.serialize();
+                var temp = contributor.serialize();
+                var minInfo = {id: temp.id, permission: temp.permission, registered: temp.registered, visible: temp.visible};
```
Comment (sloria) [inline website/static/js/contribManager.js]: @Ghalko What is the purpose of this extra serialization step?

**Comment by sloria** [comment]
Pass finished. Just had one question above. Once that's addressed, good to merge. :+1:

**Comment by Ghalko** [comment]
@sloria Fixed the camelCase, pureComputed, and the extra step that I was stripping out spurious information for submission. It was after seeing how much data we were passing through. Removed it so the code is more streamlined.
