### PR TITLE
[Hotfix] Add support and tests for datetimes with offsets

### LINKED ISSUE #3507: Date parsing function (in OSF Helpers I think) doesn't handle all ISO 8601 datetimes
Steps
====
Go to: https://osf.io/share/?q=*&optional=source%3Adailyssrn&sort=Relevance

Expected
=======
The release date would be parsed and displayed

Actual
=====
The date parsing function fails to parse a datetime string of the form ```YYYY-MM-DDTHH:mm:SS+00:00``` where the ```+00:00``` has equivalent meaning to ```Z``` (UTC +0 timezone). Instead "Invalid date" is displayed.

This also has the implication that if you ever wanted to display a datetime that had a non-UTC time zone, it would fail.

Related to #3176

### PR DESCRIPTION
**Pull request by fabianvf**
Purpose
======
Fix #3507 (Datetimes with offsets don't parse correctly in OSF FormattableDate)

Changes
=======
Do the initial datestring parsing with moment, update the logic for checking when to coerce to UTC.
Also broke up the tests for more granular failures.

Side-effects
=========
This could change how any/every date on the osf displays.

### CODE REVIEW

File: website/static/js/osfHelpers.js [hunk 1]
```diff
@@ -466,6 +468,32 @@ var applyBindings = function(viewModel, selector) {
...
+    return !((time.indexOf('+') !== -1) || (time.indexOf('-') !== -1));
+};
+
+/**
+ * A function that coerces a Datetime with no offset to a Datetime with
+ * an offset of UTC +00 (equivalent to Z)
+ * @param {String} dateTimeString The original Datetime string, which may or may not
+ *                                have a terminating Z implying UTC +00
+ */
+var forceUTC = function(dateTimeString) {
```
Comment (sloria) [inline website/static/js/osfHelpers.js]: `forceUTC` is already defined, and it appears to be identical to this.

Comment (sloria) [inline website/static/js/osfHelpers.js]: I'll remove the duplicate when I merge.
