### PR TITLE
[hotfix] Fix figshare deleting public files

### LINKED ISSUE #2183: [Staging & Production] Figshare Deletion
# Steps
1.  Link both a private and public fileset dataset to a project
2.  Go to the file viewer
3.  Hover near download button of a public file attempting to delete

# Expected
The user is allowed to delete files from public file sets unless there’s only one file left in the fileset.

# Proposal 
This is currently working, but seems unclear to the user that should be the case.  Perhaps the terms modal should be edited to explain this scenario.

### PR DESCRIPTION
**Pull request by samanehsan**
Purpose
-----------
Fixes #2183 

The delete button was showing up in the files grid toolbar for public figshare files that cannot be deleted. 

Changes
------------
Ensure public figshare files in a project do not have the delete button in the files toolbar unless they are part of a dataset that has multiple files.

### CODE REVIEW

File: website/addons/figshare/static/figshareFangornConfig.js [hunk 1]
```diff
@@ -34,9 +34,9 @@ var _figshareItemButtons = {
                 }, 'Download')
             );
         }
-        // Files can be deleted if private or if parent contains more than one child
+        // Files can be deleted if private or if it is in a dataset that contains more than one file
         var privateOrSiblings = (item.data.extra && item.data.extra.status !== 'public') ||
-            item.parent().children.length > 1;
+            (item.parent().data.isAddonRoot !== true && item.parent().children.length > 1);
```
Comment (sloria) [inline website/addons/figshare/static/figshareFangornConfig.js]: No need to compare to `true`. Just do `!item.parent().data.isAddonRoot`

**Comment by sloria** [comment]
Just a minor change and this is good to merge. :point_up:

**Comment by samanehsan** [comment]
Just made that change @sloria! :raised_hands:
